# Generated by Django 5.1 on 2024-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_post_id_alter_post_permalink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='permalink',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
